In [6]:
import pandas as pd

data = pd.read_csv('../data/datathon_data.csv')

In [7]:
data

# BELNR: Belegnummer
# WAERS: Währung
# BUKRS: Buchungskreis
# KTOSL: Kontenschlüssel
# PRCTR: Profit Center
# BSCHL: Buchungsschlüssel
# HKONT: Hauptbuchkonto
# DMBTR: Betrag in Lokaler Währung
# WRBTR: Betrag in Währung

,BELNR,WAERS,BUKRS,KTOSL,PRCTR,BSCHL,HKONT,DMBTR,WRBTR,label
0,0,C3,C31,C9,C92,A3,B1,280979.60,0.00,regular
1,1,C1,C18,C7,C76,A1,B2,129856.53,243343.00,regular
2,2,C1,C19,C2,C20,A1,B3,957463.97,3183838.41,regular
3,3,C4,C48,C9,C95,A2,B1,2681709.51,28778.00,regular
4,4,C5,C58,C1,C19,A3,B1,910514.49,346.00,regular
...,...,...,...,...,...,...,...,...,...,...
533004,533004,C1,C18,C3,C32,A1,B2,2501589.15,0.00,regular
533005,533005,C8,C80,C1,C11,A1,B1,390076.18,12065.45,regular
533006,533006,C1,C10,C1,C19,A1,B1,192147.38,326823.09,regular
533007,533007,C1,C14,C4,C40,A1,B3,870539.68,0.00,regular
533008,533008,C8,C80,C7,C78,A1,B2,532106.87,32467.08,regular

In [8]:
regular_data = data[data['label'] == 'regular']  
regular_data

,BELNR,WAERS,BUKRS,KTOSL,PRCTR,BSCHL,HKONT,DMBTR,WRBTR,label
0,0,C3,C31,C9,C92,A3,B1,280979.60,0.00,regular
1,1,C1,C18,C7,C76,A1,B2,129856.53,243343.00,regular
2,2,C1,C19,C2,C20,A1,B3,957463.97,3183838.41,regular
3,3,C4,C48,C9,C95,A2,B1,2681709.51,28778.00,regular
4,4,C5,C58,C1,C19,A3,B1,910514.49,346.00,regular
...,...,...,...,...,...,...,...,...,...,...
533004,533004,C1,C18,C3,C32,A1,B2,2501589.15,0.00,regular
533005,533005,C8,C80,C1,C11,A1,B1,390076.18,12065.45,regular
533006,533006,C1,C10,C1,C19,A1,B1,192147.38,326823.09,regular
533007,533007,C1,C14,C4,C40,A1,B3,870539.68,0.00,regular
533008,533008,C8,C80,C7,C78,A1,B2,532106.87,32467.08,regular

In [9]:
anomal_data = data[data['label'] == 'anomal']
anomal_data

,BELNR,WAERS,BUKRS,KTOSL,PRCTR,BSCHL,HKONT,DMBTR,WRBTR,label
12939,12939,C1,C20,C1,C18,A1,B1,9.106583e+05,5.444984e+04,anomal
32317,32317,C1,C11,C1,C53,A1,B1,9.106530e+05,5.443921e+04,anomal
33365,33365,W59,C13,P83,I73,I05,Q99,9.244552e+07,5.958504e+07,anomal
34058,34058,C1,C11,C1,C91,A1,B1,9.106689e+05,5.444086e+04,anomal
34059,34059,C1,C11,C1,C64,A1,B1,9.106316e+05,5.444328e+04,anomal
...,...,...,...,...,...,...,...,...,...,...
506926,506926,U72,D58,E35,Y05,D53,F61,9.244551e+07,5.958505e+07,anomal
507636,507636,C1,C11,C1,C70,A1,B1,9.106766e+05,5.444176e+04,anomal
528449,528449,C89,S43,E40,Y34,L29,N28,9.244553e+07,5.958504e+07,anomal
528759,528759,P36,V48,Z17,J68,Q50,J62,9.244554e+07,5.958504e+07,anomal
532375,532375,C1,C11,C1,C75,A1,B1,9.106505e+05,5.444948e+04,anomal

In [10]:
display(regular_data.describe())
display(anomal_data.describe())

               BELNR         DMBTR         WRBTR
count  532909.000000  5.329090e+05  5.329090e+05
mean   266499.244000  9.106470e+05  5.444185e+04
std    153867.424557  1.879574e+06  4.399818e+05
min         0.000000  2.600000e+00  0.000000e+00
25%    133248.000000  2.159054e+05  0.000000e+00
50%    266496.000000  4.863084e+05  0.000000e+00
75%    399754.000000  9.749580e+05  2.626600e+04
max    533008.000000  9.244552e+07  5.958504e+07

               BELNR         DMBTR         WRBTR
count     100.000000  1.000000e+02  1.000000e+02
mean   291849.150000  6.498506e+07  4.172586e+07
std    147923.052578  4.215787e+07  2.741778e+07
min     12939.000000  9.106316e+05  5.442850e+04
25%    181820.000000  9.106592e+05  5.445207e+04
50%    317239.500000  9.244551e+07  5.958504e+07
75%    405805.000000  9.244552e+07  5.958504e+07
max    532375.000000  9.244554e+07  5.958506e+07