In [8]:
import pandas as pd

data = pd.read_csv('../data/datathon_data.csv')

In [10]:
data

,BELNR,WAERS,BUKRS,KTOSL,PRCTR,BSCHL,HKONT,DMBTR,WRBTR,label
0,0,C3,C31,C9,C92,A3,B1,280979.60,0.00,regular
1,1,C1,C18,C7,C76,A1,B2,129856.53,243343.00,regular
2,2,C1,C19,C2,C20,A1,B3,957463.97,3183838.41,regular
3,3,C4,C48,C9,C95,A2,B1,2681709.51,28778.00,regular
4,4,C5,C58,C1,C19,A3,B1,910514.49,346.00,regular
...,...,...,...,...,...,...,...,...,...,...
533004,533004,C1,C18,C3,C32,A1,B2,2501589.15,0.00,regular
533005,533005,C8,C80,C1,C11,A1,B1,390076.18,12065.45,regular
533006,533006,C1,C10,C1,C19,A1,B1,192147.38,326823.09,regular
533007,533007,C1,C14,C4,C40,A1,B3,870539.68,0.00,regular
533008,533008,C8,C80,C7,C78,A1,B2,532106.87,32467.08,regular